# Usar la imagen oficial de nginx como base
FROM nginx:alpine

# Copiar el archivo index.html al contenedor en la ruta donde nginx busca los archivos
COPY index.html /usr/share/nginx/html/index.html

# Exponer el puerto 80 para acceder a la aplicación
EXPOSE 80
