version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fintech_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data  # Volumen persistente para los datos de PostgreSQL
    networks:
      - fintech_network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - fintech_network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - fintech_network

volumes:
  pg_data:  # Definir el volumen persistente para PostgreSQL
  
networks:
  fintech_network:
    driver: bridge
